name: pnpmi
description: 'Default pnpm create action'

inputs:
  branch:
    token: 'Your NPM TOKEN'
    required: true
    type: string

runs:
  using: 'composite'

  steps:
    - uses: JS-DevTools/npm-publish@v3
        id: publish
        name: Publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          strategy: upgrade
          
    - name: Check - updated
      if: ${{ steps.publish.outputs.type }}
      run:
        echo "${{ steps.publish.outputs.name }} Version changed from ${{
        steps.publish.outputs.old-version }} to ${{
        steps.publish.outputs.version }}"

    - name: Check - not updated
      if: ${{ ! steps.publish.outputs.type }}
      run: echo "Remain the same! - ${{ steps.publish.outputs.version }}"